CREATE
OR REPLACE PROCEDURE BCCS_SALE (
    p_sub_id           IN NUMBER,
    p_contract_id      IN NUMBER,
    p_account_id       IN NUMBER,
    p_cust_identity_id IN NUMBER,
    p_cust_id          IN NUMBER
) IS
BEGIN
INSERT INTO CUSTOMER (CUST_ID,
                      CUST_TYPE,
                      NAME,
                      BIRTH_DATE,
                      SEX,
                      NATIONALITY,
                      VIP,
                      STATUS,
                      AREA_CODE,
                      PROVINCE,
                      DISTRICT,
                      PRECINCT,
                      STREET_BLOCK,
                      STREET,
                      STREET_NAME,
                      STREET_BLOCK_NAME,
                      HOME,
                      ADDRESS,
                      CREATE_USER,
                      CREATE_DATETIME,
                      UPDATE_DATETIME,
                      UPDATE_USER,
                      DESCRIPTION,
                      UPDATE_NUMBER2,
                      LAST_MODIFIED,
                      PARENT_ID)
VALUES (p_cust_id,
        'VIE',
        'TEST DIA BAN',
        TO_DATE('2025-06-05 09:22:51', 'YYYY-MM-DD HH24:MI:SS'),
        'M',
        'Việt Nam',
        NULL,
        '1',
        'HNI0400060',
        'HNI',
        NULL,
        '040',
        '0060',
        NULL,
        NULL,
        'Tổ 1-Bồ Đề',
        NULL,
        'Tổ 1-Bồ Đề, Phường Bồ Đề Thành phố Hà Nội',
        'VTT1',
        TO_DATE('2025-06-12 14:02:28', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2025-10-14 18:17:39', 'YYYY-MM-DD HH24:MI:SS'),
        'VTT1',
        NULL,
        NULL,
        NULL,
        NULL);

INSERT INTO CUST_IDENTITY (CUST_IDENTITY_ID,
                           CUST_ID,
                           ID_TYPE,
                           ID_NO,
                           ID_ISSUE_PLACE,
                           ID_ISSUE_DATE,
                           ID_EXPIRE_DATE,
                           CREATE_USER,
                           CREATE_DATETIME,
                           UPDATE_USER,
                           UPDATE_DATETIME,
                           STATUS)
VALUES (p_cust_identity_id,
        p_cust_id,
        'IDC',
        LPAD(TRUNC(DBMS_RANDOM.VALUE(0, 999999999999)), 12, '0'),
        'Hà Nội',
        TO_DATE('2013-10-23', 'YYYY-MM-DD HH24:MI:SS'),
        NULL,
        'VTT1',
        TO_DATE('2025-06-12 14:02:28', 'YYYY-MM-DD HH24:MI:SS'),
        'VTT1',
        TO_DATE('2025-12-11 09:22:51', 'YYYY-MM-DD HH24:MI:SS'),
        '1');

INSERT INTO ACCOUNT (ACCOUNT_ID,
                     CUST_ID,
                     BILL_CYCLE_ID,
                     ACCOUNT_NO,
                     LIMIT_USAGE,
                     NOTICE_CHARGE,
                     RECEIVE_INVOICE,
                     END_DATETIME,
                     AREA_CODE,
                     PROVINCE,
                     DISTRICT,
                     PRECINCT,
                     STREET_BLOCK,
                     STREET,
                     STREET_NAME,
                     STREET_BLOCK_NAME,
                     HOME,
                     ADDRESS,
                     STATUS,
                     CREATE_USER,
                     CREATE_DATETIME,
                     UPDATE_USER,
                     UPDATE_DATETIME,
                     PRINT_METHOD,
                     PAY_METHOD,
                     SUB_ID,
                     ISDN,
                     SIGN_DATE,
                     EFFECT_DATE,
                     UPDATE_NUMBER)
VALUES (p_account_id,
        p_cust_id,
        1,
        LPAD(TRUNC(DBMS_RANDOM.VALUE(0, 9999999999)), 10, '0'),
        NULL,
        '4',
        NULL,
        NULL,
        'H004007004001',
        'H004',
        '007',
        '004',
        '001',
        NULL,
        NULL,
        'Tổ 1',
        NULL,
        'Tổ 1, Dịch Vọng Cầu Giấy Hà Nội',
        '2',
        'VTT1',
        TO_DATE('2025-06-12 14:02:28', 'YYYY-MM-DD HH24:MI:SS'),
        'VTT1',
        TO_DATE('2025-12-11 09:22:51', 'YYYY-MM-DD HH24:MI:SS'),
        '2',
        '00',
        60000345761,
        '24721010301',
        TO_DATE('2025-06-12', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2025-06-12', 'YYYY-MM-DD HH24:MI:SS'),
        NULL);

INSERT INTO SUBSCRIBER (SUB_ID,
                        CONTRACT_ID,
                        CUST_ID,
                        ACCOUNT_ID,
                        TELECOM_SERVICE_ID,
                        ISDN,
                        IMSI,
                        SERIAL,
                        STATUS,
                        PRODUCT_CODE,
                        OFFER_ID,
                        ACT_STATUS,
                        STA_DATETIME,
                        ACTIVE_DATETIME,
                        SUB_TYPE,
                        END_DATETIME,
                        EXPIRE_DATETIME,
                        SHOP_CODE,
                        DEV_STAFF_ID,
                        PROMOTION_CODE,
                        VIP,
                        ACCOUNT,
                        CREATE_DATETIME,
                        CREATE_USER,
                        UPDATE_DATETIME,
                        UPDATE_USER,
                        DEPOSIT,
                        LIMIT_USAGE,
                        PASSWORD,
                        ORG_PRODUCT_CODE,
                        NUM_RESET_ZONE,
                        START_MONEY,
                        IS_INFO_COMPLETED,
                        CHANNEL_TYPE_ID,
                        FIRST_CONNECT,
                        SPEED,
                        KEEP_ALIVE,
                        PRICE_PLAN,
                        LOCAL_PRICE_PLAN,
                        PROJECT,
                        LOCAL_SPEED,
                        TECHNOLOGY,
                        NETWORK_CLASS,
                        INFRASTRUCTURE_TYPE,
                        DEPLOY_ACCEPT_DATE,
                        GROUP_ID,
                        IP_STATIC,
                        IP_VIEW,
                        IP_LAN,
                        IP_WAN,
                        IP_GATEWAY,
                        IP_ROUTER,
                        NUM_OF_COMPUTER,
                        VLAN,
                        UP_LINK,
                        PRIVATE_IP,
                        PAY_TYPE,
                        UPDATE_NUMBER_1,
                        REG_TYPE_ID,
                        UPDATE_NUMBER3,
                        TYPE,
                        UPDATE_NUMBER)
VALUES (p_sub_id,
        p_contract_id,
        p_cust_id,
        p_account_id,
        1,
        LPAD(TRUNC(DBMS_RANDOM.VALUE(0, 99999999999)), 11, '0'),
        '452040951047528',
        '8984048000951047528',
        '2',
        'POBAS',
        400000607,
        '010',
        TO_DATE('2025-10-14 20:00:34', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2025-10-14 20:00:34', 'YYYY-MM-DD HH24:MI:SS'),
        'VIE',
        NULL,
        NULL,
        'VT',
        NULL,
        'SG084',
        NULL,
        NULL,
        TO_DATE('2025-10-14 20:00:34', 'YYYY-MM-DD HH24:MI:SS'),
        'VTT1',
        TO_DATE('2025-12-11 09:22:51', 'YYYY-MM-DD HH24:MI:SS'),
        'VTT1',
        0,
        100000000,
        NULL,
        'Vconnect_F',
        NULL,
        NULL,
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        7003389050,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        9003992371,
        NULL,
        NULL);

COMMIT;
END;
